--- #YAML:1.0
name: Posy-Plugin-ShortBody
version: 0.50
author:
  - Kathryn Andersen
abstract: Posy plugin to give the start of an entry body
license: perl
requires:
  Posy: 0.4
build_requires:
  Test::More: 0
provides:
  Posy::Plugin::ShortBody:
    file: lib/Posy/Plugin/ShortBody.pm
    version: 0.50
generated_by: Module::Build version 0.2607
